### ISSUE TITLE
Are all the tasks v3?

### ISSUE THREAD

**Issue by red-tie** [x35f/unstable_baselines#46]
I see that the current performance curve is based on v3 tasks. However, the config file in the model based RL (mbpo) contains many v2 tasks. Are the v2 tasks in the mbpo same as v3 tasks?

**Comment by typoverflow** [comment]
cc @x35f

**Comment by x35f** [comment]
Hi, the current performance curve of MBPO in Hopper,  HalfCheetah and Walker2d are based on the v3 tasks. The original MBPO implementation made some changes to the default Ant and Humanoid v2 environment (please refer to https://github.com/jannerm/mbpo and the unstable_baselines/envs/mbpo directory for details), and we retained them. The performance curve of MBPO in Ant and Humanoid are actually evaluated on these modified versions of tasks.
